import { createApp } from 'vue'
// import './style.css'
// import App from './App.vue'
// import App from './components/demo001.vue'
//import App from './components/demo002.vue'
// import App from './components/demo003.vue'
// import App from './components/demo004.vue'
// import App from './components/demo005.vue'
// import App from './components/demo006.vue'
// import App from './components/demo007.vue'
// import App from './components/demo_v-text.vue'
// import App from './components/demo_v-html.vue'
// import App from './components/demo_v-bind.vue'
import App from './components/demo_v-on.vue'
createApp(App).mount('#app')
